spring.datasource.url=jdbc:mysql://localhost:3306/login_db
spring.datasource.username=root
spring.datasource.password=Shreya@19

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.thymeleaf.cache=false

aws.region=eu-north-1
aws.s3.bucket=springboot-login-file-upload-shreya